services:
  postgres:
    image: postgres:15
    container_name: postgres-crud-app
    environment:
      POSTGRES_DB: crud_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
